version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "BAU"
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "BAU"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: BAU
