name: AWS build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@943103cae7d3f1bb1e4951d5fcc7928b40e4b742 # pin@v1
        with:
          bundler-cache: true
      - name: Install Gems
        run: bundle install

      - name: Build
        run: bundle exec middleman build

      - name: Upload to ECR and tag
        uses: govuk-one-login/devplatform-upload-action-ecr@2670d3fde00e5e9eed187135e853f273763cab02 # pin@1.2.4
        with:
          role-to-assume-arn: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET }}
          dockerfile: "./DockerfileAWS"
          checkout-repo: false
